from __future__ import annotations

from datetime import datetime
from typing import Protocol

from sandbox.domain.entities import UserSandboxBindingRecord, SandboxRecord


class BindingManager(Protocol):
    async def find_user_binding(self, user_id: str) -> UserSandboxBindingRecord | None: ...

    async def binding_for_sandbox(self, sandbox_id: str) -> UserSandboxBindingRecord | None: ...

    async def user_bindings(self) -> list[UserSandboxBindingRecord]: ...

    async def idle_user_bindings(self, now: datetime | None = None) -> list[UserSandboxBindingRecord]: ...

    async def expired_idle_user_bindings(self, now: datetime | None = None) -> list[UserSandboxBindingRecord]: ...

    async def activate_user_binding(self, sandbox_id: str) -> SandboxRecord: ...

    async def clear_binding(self, record: SandboxRecord) -> None: ...